# Generated by Django 5.2.9 on 2026-01-03 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_even_organiz_266ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_even_starts__b01102_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_0ae1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event'], name='events_even_event_i_9a7faf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user'], name='events_even_user_id_db990f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['created_at'], name='events_even_created_60dc75_idx'),
        ),
    ]
